#! /bin/sh

echo $HOSTNAME | grep gridley.ece.Virginia.EDU > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 262814 
else 
ssh gridley.ece.Virginia.EDU kill 262814 
 sleep 10 
ssh gridley.ece.Virginia.EDU kill -9 262814 
fi
