*********************************************************/

BLOCK: XO_2_0
*MILKYWAY_DATABASE: /remote/SCRATCH_sym1/khtigran/14nm_FinFET/PDK/puzzle/layout_test/synopsys_custom/n08_tt.icv.lvs/XTROUT
TCAD_GRD_FILE: ./starrc/nominal/saed14nm_1p9m_nominal.nxtgrd
**MAPPING_FILE: /remote/SCRATCH_sym1/khtigran/14nm_FinFET/PDK/puzzle/layout_test/synopsys_custom/n08_tt.icv.lvs/pex_process_map_file
**MAPPING_FILE: /remote/exchange/synopsys/SAED32_PDK/starrc/oa_layer.map
ICV_RUNSET_REPORT_FILE:./pex_runset_report
**ITF_FILE: /remote/SCRATCH_sym1/khtigran/14nm_FinFET/PDK/puzzle/icv/starrc/saed14nm_1p9m_nominal.itf

MULTIGATE_MODELS: YES
COUPLE_TO_GROUND: NO
COUPLING_MULTIPLIER: 1
*EXTRACTION: RC
MILKYWAY_EXTRACT_VIEW: YES
CASE_SENSITIVE: NO
NETLIST_FORMAT: SPF
NETLIST_NODE_SECTION: YES
NETLIST_CONNECT_SECTION: YES
NETLIST_SUBCKT: YES
NETLIST_PASSIVE_PARAMS: YES
NETLIST_TAIL_COMMENTS: YES
NETLIST_DELIMITER: :
REDUCTION: NO
XREF: YES
EXTRACT_VIA_CAPS: NO
IGNORE_CAPACITANCE: NONE
KEEP_VIA_NODES: NO
MAGNIFY_DEVICE_PARAMS:NO
METAL_FILL_POLYGON_HANDLING: IGNORE
**MODE: 200
MOS_GATE_DELTA_RESISTANCE: NO
REMOVE_DANGLING_NETS: NO
REMOVE_FLOATING_NETS: NO
TRANSLATE_RETAIN_BULK_LAYERS: YES
SKIP_CELLS: !*
HIERARCHICAL_SEPARATOR: |
*OBSERVATION_POINTS: *
EXTRA_GEOMETRY_INFO: NODE

HN_NETLIST_SPICE_TYPE: n08 X
HN_NETLIST_SPICE_TYPE: p08 X
HN_NETLIST_SPICE_TYPE: n08_lvt X
HN_NETLIST_SPICE_TYPE: p08_lvt X
HN_NETLIST_SPICE_TYPE: n08_hvt X
HN_NETLIST_SPICE_TYPE: p08_hvt X
HN_NETLIST_SPICE_TYPE: n08_slvt X
HN_NETLIST_SPICE_TYPE: p08_slvt X
HN_NETLIST_SPICE_TYPE: n18 X
HN_NETLIST_SPICE_TYPE: p18 X
HN_NETLIST_SPICE_TYPE: n15 X
HN_NETLIST_SPICE_TYPE: p15 X
HN_NETLIST_SPICE_TYPE: ccap X

OA_LIB_NAME:
OA_VIEW_NAME: starrc
OA_MARKER_SIZE: 0.1
OA_REMOVE_SPICECARD_PREFIX: NO
OA_DEVICE_MAPPING_FILE: ../starrc/saed14nm_1p9m_device.map
